---
- name: Reload HTTPD
  become: true
  service:
    name: httpd.service
    state: reloaded
  listen: reload httpd

- name: Update Nextcloud to expected version
  become: true
  unarchive:
    src: https://download.nextcloud.com/server/releases/nextcloud-{{ nextcloud.version }}.tar.bz2 # yamllint disable-line
    dest: /var/www/html/
    extra_opts:
      - --strip-components=1
      - --selinux
    remote_src: true
    owner: apache
    group: apache
  listen: update nextcloud version

- name: Install Nextcloud
  become: true
  become_user: apache
  command: |
    php /var/www/html/occ maintenance:install     \
      --database=pgsql                            \
      --database-name=nextcloud                   \
      --database-host={{ nextcloud.db_host }}     \
      --database-user={{ nextcloud.db_username }} \
      --database-pass={{ nextcloud.db_password }} \
      --database-table-prefix=nc_                 \
      --admin-user={{ nextcloud.admin_username }} \
      --admin-pass={{ nextcloud.admin_password }} \
      --data-dir=/var/www/html/data
  listen: install nextcloud

- name: Update Nextcloud .htaccess file
  become: true
  become_user: apache
  command: php /var/www/html/occ maintenance:update:htaccess
  listen: update nextcloud htaccess
