---
- name: Install Traefik
  become: true
  get_url:
    url: https://github.com/containous/traefik/releases/download/v{{ traefik.version }}/traefik_linux-amd64
    dest: /usr/sbin/traefik
    mode: 0755
    force: true
  listen: install traefik
  notify:
    - restart traefik

- name: Restart Traefik
  become: true
  systemd:
    state: restarted
    name: traefik.service
    daemon_reload: true
  listen: restart traefik
